#!/bin/bash

#This script will run through several checks and for each check output to the terminal 'OK' or 'ERROR
#The checks are designed to test whether or not the host conforms to the benchmarks in the
#following document
#https://benchmarks.cisecurity.org/tools2/linux/CIS_CentOS_Linux_7_Benchmark_v1.1.0.pdf

#This is aimed to be a starting point for a sysadmin to check or audit hosts he/she supports
#It's envisaged that it will need customising to suit a particular environment
#e.g. there are about 200 checks, someone may want to chop out X of them to suit their environment
#The script does not change anything on the host, mostly it runs a lot of greps & cuts
#on config files.
#To quickly get an idea of what this script does have a look at the 'main' and 'func_wrapper' functions
#Copyright (c) 2015, Ross Hamilton. All rights reserved.

source $(dirname -- "$0")/test-utils.sh
source $(dirname -- "$0")/test-functions.sh

autopass=()
excluded=()
requested=()
todo=0
level_1_count=0
level_1_scored=0
level_1_pass=0
level_1_fail=0
level_1_todo=0
level_2_count=0
level_2_scored=0
level_2_pass=0
level_2_fail=0
level_2_todo=0

function usage() {
	cat <<-EOF
		Usage: $0 [-h|--help] [-a|--autopass test-name] [-e|--exclude test-name] [-l|--list] [test-name [test-name ...]]

		-h		This message
		-a		Auto pass test named "test-name"
		-e		Exclude test named "test-name" entirely
		-l		List tests
		test-name 	The CIS number for a test (can be used multiple times)
	EOF
}

function parse_options() {
	while (($#))
	do
		case "$1" in
			-h|--help|-\?) usage; exit 0;;
			-a|--autopass) autopass+=("$2"); shift;;
			-e|--exclude) excluded+=("$2"); shift;;
			*) requested+=("$1");;
		esac

		shift
	done
}


function func_wrapper {
	local auto_pass=0 infowidth=60

	if [[ "$1" == "-n" ]]
	then
		cis_number="$2"
		shift 2
		cis_level="$1"
		shift
	fi

	func_name="$1"
	shift
	args=("$@")

	if [[ -n $cis_number ]]
	then
		printf "CIS %-10s " $cis_number

		for test in "${autopass[@]}"
		do
			[[ $test == $cis_number ]] && {
				auto_pass=1
			}
		done
	fi

	case "$func_name" in
		todo)
			((++todo))
			((cis_level > 0)) && let "level_${cis_level}_todo++"
			local info="${args[*]}"
			(( ${#info} > infowidth )) && info="${info:0:$((infowidth-1))}…"
			printf "%-${infowidth}s TODO\n" "$info"
		;;
		*)
			local info="$func_name ${args[*]}"
			(( ${#info} > infowidth )) && info="${info:0:$((infowidth-1))}…"
			printf "%-${infowidth}s " "$info"

			if ((auto_pass))
			then
				echo AUTOPASS
				return 0

			elif ${func_name} "${args[@]}"
			then
				echo OK

			else
				echo FAIL
				return 1
			fi
		;;
	esac
}

tests=(
	$'1.1.1.1:1:test_disable_mounting:cramfs'
	$'1.1.1.2:1:test_disable_mounting:freevxfs'
	$'1.1.1.3:1:test_disable_mounting:jffs2'
	$'1.1.1.4:1:test_disable_mounting:hfs'
	$'1.1.1.5:1:test_disable_mounting:hfsplus'
	$'1.1.1.6:1:test_disable_mounting:squashfs'
	$'1.1.1.7:1:test_disable_mounting:udf'
	$'1.1.1.8:1:test_disable_mounting:fat'

	$'1.1.2:2:separate_partition:/tmp'
	$'1.1.3:1:mount_option:/tmp\tnodev'
	$'1.1.4:1:mount_option:/tmp\tnosuid'
	$'1.1.5:1:mount_option:/tmp\tnoexec'
	$'1.1.6:2:separate_partition:/var'
	$'1.1.7:2:separate_partition:/var/tmp'
	$'1.1.8:1:mount_option:/var/tmp\tnodev'
	$'1.1.9:1:mount_option:/var/tmp\tnosuid'
	$'1.1.10:1:mount_option:/var/tmp\tnoexec'
	$'1.1.11:2:separate_partition:/var/log'
	$'1.1.12:2:separate_partition:/var/log/audit'
	$'1.1.13:2:separate_partition:/home'
	$'1.1.14:1:mount_option:/home\tnodev'
	$'1.1.15:1:mount_option:/dev/shm\tnodev'
	$'1.1.16:1:mount_option:/dev/shm\tnosuid'
	$'1.1.17:1:mount_option:/dev/shm\tnoexec'
	$'1.1.18:-1:todo:nodev on removable media'
	$'1.1.19:-1:todo:nosuid on removable media'
	$'1.1.20:-1:todo:noexec on removable media'
	$'1.1.21:1:sticky_wrld_w_dirs'
	$'1.1.22:1:check_svc_not_enabled:autofs'

	$'1.2.1:-1:todo:yum repos'
	$'1.2.2:-1:centos_gpg_key_installed'
	$'1.2.3:1:yum_gpgcheck'

	$'1.3.1:1:rpm_installed:aide'
	$'1.3.2:1:verify_aide_cron'

	"1.4.1:1:check_root_owns:${GRUB_CFG}"
	$'1.4.2:1:check_boot_pass'
	$'1.4.3:-1:todo:single user auth'

	$'1.5.1:1:restrict_core_dumps'
	$'1.5.2:-1:todo:XD/NX'
	$'1.5.3:1:chk_sysctl:kernel.randomize_va_space\t2'
	$'1.5.4:1:todo:prelink'

	$'1.6.1.1:2:verify_selinux_grubcfg'
	$'1.6.1.2:2:verify_selinux_state'
	$'1.6.1.3:2:verify_selinux_policy'
	$'1.6.1.4:2:rpm_not_installed:setroubleshoot'
	$'1.6.1.5:2:rpm_not_installed:mcstrans'
	$'1.6.1.6:2:unconfined_procs'
	$'1.6.2:2:rpm_installed:libselinux'

	$'1.7.1.1:1:check_disallowed_expansions:/etc/motd'
	$'1.7.1.2:-1:check_disallowed_expansions:/etc/issue'
	$'1.7.1.3:-1:check_disallowed_expansions:/etc/issue.net'

	$'1.7.1.4:-1:check_owner_group_perms:/etc/motd\t0\t0\t644'
	$'1.7.1.5:1:check_owner_group_perms:/etc/issue\t0\t0\t644'
	$'1.7.1.6:-1:check_owner_group_perms:/etc/issue.net\t0\t0\t644'

	$'1.7.2:1:gdm_login_banner'

	$'1.8:-1:yum_update'

	$'2.1.1:1:check_svc_not_enabled:chargen-dgram\tchargen-stream'
	$'2.1.2:1:check_svc_not_enabled:daytime-dgram\tdaytime-stream'
	$'2.1.3:1:check_svc_not_enabled:discard-dgram\tdiscard-stream'
	$'2.1.4:1:check_svc_not_enabled:echo-dgram\techo-stream'
	$'2.1.5:1:check_svc_not_enabled:time-dgram\ttime-stream'
	$'2.1.6:1:check_svc_not_enabled:tftp'
	$'2.1.7:1:check_svc_not_enabled:xinetd' # TODO we use this

	$'2.2.1.1:-1:time_sync_in_use'
	$'2.2.1.2:1:ntp_is_configured'
	$'2.2.1.3:1:chrony_is_configured'


	$'2.2.2:1:x_not_installed'
	$'2.2.3:1:check_svc_not_enabled:avahi-daemon'
	$'2.2.4:1:check_svc_not_enabled:cups'
	$'2.2.5:1:check_svc_not_enabled:dhcpd'
	$'2.2.6:1:check_svc_not_enabled:slapd'
	$'2.2.7:1:check_svc_not_enabled:nfs\trpcbind'
	$'2.2.8:1:check_svc_not_enabled:named'
	$'2.2.9:1:check_svc_not_enabled:vsftpd'
	$'2.2.10:1:check_svc_not_enabled:httpd'
	$'2.2.11:1:check_svc_not_enabled:dovecot'
	$'2.2.12:1:check_svc_not_enabled:smb'
	$'2.2.13:1:check_svc_not_enabled:squid'
	$'2.2.14:1:check_svc_not_enabled:snmpd'
	$'2.2.15:1:check_mta'
	$'2.2.16:1:check_svc_not_enabled:ypserv'
	$'2.2.17:1:check_svc_not_enabled:rsh.socket\trlogin.socket\trexec.socket'
	$'2.2.18:1:check_svc_not_enabled:telnet.socket'
	$'2.2.19:1:check_svc_not_enabled:tftp.socket'
	$'2.2.20:1:check_svc_not_enabled:rsyncd'
	$'2.2.21:1:check_svc_not_enabled:ntalk'

	$'2.3.1:1:rpm_not_installed:ypbind'
	$'2.3.2:1:rpm_not_installed:rsh'
	$'2.3.3:1:rpm_not_installed:talk'
	$'2.3.4:1:rpm_not_installed:telnet'
	$'2.3.5:1:rpm_not_installed:openldap-clients'

	$'3.1.1:1:check_ip_forwarding'
	$'3.1.2:1:disable_send_redirects'

	$'3.2.1:1:reject_source_routed_packets'
	$'3.2.2:1:reject_icmp_redirects'
	$'3.2.3:1:reject_secure_icmp_redirects'
	$'3.2.4:1:log_suspicious_packets'
	$'3.2.5:1:ignore_icmp_broadcast'
	$'3.2.6:1:ignore_bogus_icmp'
	$'3.2.7:1:enable_reverse_path_filtering'
	$'3.2.8:1:enable_tcp_syn_cookies'

	$'3.3.1:1:reject_ipv6_router_advertisements'
	$'3.3.2:1:reject_ipv6_redirects'
	$'3.3.3:-1:ipv6_disabled'

	$'3.4.1:1:rpm_installed:tcp_wrappers'
	$'3.4.2:1:check_hosts_allow'
	$'3.4.3:1:check_hosts_deny'
	$'3.4.4:1:check_owner_group_perms:/etc/hosts.allow\t0\t0\t644'
	$'3.4.5:1:check_owner_group_perms:/etc/hosts.deny\t0\t0\t644'

	$'3.5.1:-1:test_module_disabled:dccp'
	$'3.5.2:-1:test_module_disabled:sctp'
	$'3.5.3:-1:test_module_disabled:rds'
	$'3.5.4:-1:test_module_disabled:tipc'

	$'3.6.1:1:rpm_installed:iptables'
	$'3.6.2:1:check_firewall_policy'
	$'3.6.3:1:check_firewall_loopback'
	$'3.6.4:-1:check_firewall_outbound'
	$'3.6.5:1:check_firewall_services'

	$'3.7:-1:check_wireless_interfaces'

	$'4.1.1.1:-2:check_audit_log_size'
	$'4.1.1.2:2:check_audit_log_full_action'
	$'4.1.1.3:3:check_audit_log_deletion'

	$'4.1.2:2:check_svc_enabled:auditd'
	$'4.1.3:2:check_boot_audit'
	$'4.1.4:2:check_audit_time_changes'
	$'4.1.5:2:check_audit_user_group_changes'
	$'4.1.6:2:check_audit_net_changes'
	$'4.1.7:2:check_audit_mac_policy_changes'
	$'4.1.8:2:check_audit_login'
	$'4.1.9:2:check_audit_session'
	$'4.1.10:2:check_audit_perm_changes'
	$'4.1.11:2:check_audit_login_failure'
	$'4.1.12:2:check_audit_privileged_commands'
	$'4.1.13:2:check_audit_mounts'
	$'4.1.14:2:check_audit_deletes'
	$'4.1.15:2:check_audit_sudoers'
	$'4.1.16:2:check_audit_sudo_log'
	$'4.1.17:2:check_audit_modules'
	$'4.1.18:2:check_audit_immutable'

	# This section only applies if rsyslog is installed on the system.
	$'4.2.1.1:1:check_svc_enabled:rsyslog'
	$'4.2.1.2:-1:check_rsyslog_configured'
	$'4.2.1.3:1:check_rsyslog_permissions'
	$'4.2.1.4:1:check_rsyslog_remote'
	$'4.2.1.5:-1:check_rsyslog_remote_accepted'

	# This section only applies if syslog-ng is installed on the system.
	$'4.2.2.1:1:check_svc_enabled:syslog-ng'
	$'4.2.2.2:-1:check_syslog_ng_configured'
	$'4.2.2.3:1:check_syslog_ng_permissions'
	$'4.2.2.4:-1:check_syslog_ng_remote'
	$'4.2.2.5:-1:check_syslog_ng_remote_accepted'

	$'4.2.3:1:check_logging_installed'
	$'4.2.4:1:check_logfile_permissions'

	$'4.3:-1:check_logrotate'

	$'5.1.1:1:check_svc_enabled:crond'
	$'5.1.2:1:check_owner_group_perms:/etc/crontab\t0\t0\t600'
	$'5.1.3:1:check_owner_group_perms:/etc/cron.hourly\t0\t0\t700'
	$'5.1.4:1:check_owner_group_perms:/etc/cron.daily\t0\t0\t700'
	$'5.1.5:1:check_owner_group_perms:/etc/cron.weekly\t0\t0\t700'
	$'5.1.6:1:check_owner_group_perms:/etc/cron.monthly\t0\t0\t700'
	$'5.1.7:1:check_owner_group_perms:/etc/cron.d\t0\t0\t700'
	$'5.1.8:1:check_cron_restrictions'

	$'5.2.1:1:check_owner_group_perms:/etc/ssh/sshd_config\t0\t0\t600'
	$'5.2.2:1:check_ssh_protocol'
	$'5.2.3:1:check_ssh_log_level'
	$'5.2.4:1:check_ssh_X_forwarding'
	$'5.2.5:1:check_ssh_max_auth_tries'
	$'5.2.6:1:check_ssh_ignore_rhosts'
	$'5.2.7:1:check_ssh_host_based_auth'
	$'5.2.8:1:check_ssh_root_login'
	$'5.2.9:1:check_ssh_empty_passwords'
	$'5.2.10:1:check_ssh_user_environment'
	$'5.2.11:1:check_ssh_ciphers'
	$'5.2.12:1:check_ssh_MACs'
	$'5.2.13:1:check_ssh_idle_timeout'
	$'5.2.14:1:check_ssh_login_grace'
	$'5.2.15:1:check_ssh_access'
	$'5.2.16:1:check_ssh_banner'

	$'5.3.1:1:todo:pam password requirements'
	$'5.3.2:1:todo:pam password failures'
	$'5.3.3:1:todo:pam password reuse'
	$'5.3.4:1:todo:pam password hash algo'

	$'5.4.1.1:1:todo:shadow password params'
	$'5.4.1.2:1:todo:password change interval'
	$'5.4.1.3:1:todo:password change interval'
	$'5.4.1.4:1:todo:password inactive lock'

	$'5.4.2:1:todo:nologin system accounts'
	$'5.4.3:1:todo:root gid'
	$'5.4.4:1:check_umask'

	$'5.5:-1:check_root_login_console'
	$'5.6:1:check_su_restrictions'

)

function new_main() {
	echo "Auto-passing: ${autopass[@]}"
	echo "Excluding: ${excluded[@]}"

	local only_requested=${#requested[@]}
	local count=0

	for test in "${tests[@]}"
	do
		IFS=$':' read cis_number level name arg <<<"$test"
		[[ $cis_number == break ]] && break
		IFS=$'\t' read -a args <<<"$arg"

		for test in "${excluded[@]}"
		do
			[[ $test == $cis_number ]] && {
				continue 2
			}
		done

		if ((only_requested))
		then
			local do_it=0
			for test in "${requested[@]}"
			do
				[[ $test == $cis_number ]] && do_it=1
			done

			((do_it)) || continue
		fi

		if ((list))
		then
			echo $cis_number "$name" "${args[@]}"
		else
			((++count))

			((level > 0)) && let "level_${level}_count++"
#			func_wrapper -n "$cis_number" "$name" "${args[@]}"
			if func_wrapper -n "$cis_number" "$level" "$name" "${args[@]}"
			then
				((level > 0)) && let "level_${level}_pass++"
			else
				((level > 0)) && let "level_${level}_fail++"
			fi
		fi
	done

	cat <<-EOF

		Level 1 Compliance: $((level_1_pass * 100 / level_1_count))%
		  Pass: $level_1_pass
		  Fail: $level_1_fail
		  TODO: $level_1_todo

		Level 2 Compliance: $((level_2_pass * 100 / level_2_count))%
		  Pass: $level_2_pass
		  Fail: $level_2_fail
		  TODO: $level_2_todo

		Overall Compliance: $(( (level_1_pass + level_2_pass) * 100 / (level_1_count + level_2_count) ))%
		  Pass: $((level_1_pass + level_2_pass))
		  Fail: $((level_1_fail + level_2_fail))
		  TODO: $((level_1_todo + level_2_todo))
	EOF
}


